# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # Node.js version to use
          cache: "npm"
          cache-dependency-path: '**/package-lock.json' # Path to package-lock.json file for caching
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT} 
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-    
      - run: npm ci
      - run: npm run start
      - run: npm run build --if-present
      - run: npm test
      - uses: Eun/http-server-action@v1
        with:
          port: 80
          index: index.html
          root: ./dist
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./ # Directory to serve files from
          check_html: true # Check HTML files for errors
          check_links: true # Check links in HTML files
          check_css: true # Check CSS files for errors
          check_js: true # Check JS files for errors
          enforce_https: true # Enforce HTTPS for links
          check_images: true # Check images for errors
         
      
