# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}   
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - uses: Eun/http-server-action@v1
        with:
          port: 80
          index: index.html
          root: ./dist
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./ # Directory to serve files from
          check_html: true # Check HTML files for errors
          check_links: true # Check links in HTML files
          check_css: true # Check CSS files for errors
          check_js: true # Check JS files for errors
          enforce_https: true # Enforce HTTPS for links
          check_images: true # Check images for errors
         
      
